Update docker-publish-gpr.yml

diff --git a/.github/workflows/docker-publish-gpr.yml b/.github/workflows/docker-publish-gpr.yml
--- a/.github/workflows/docker-publish-gpr.yml
+++ b/.github/workflows/docker-publish-gpr.yml
@@ -21,8 +21,16 @@ jobs:
 
       - name: Free up disk space
         run: |
+          df -h
           sudo rm -rf /usr/local/lib/android || true
+          df -h
           sudo rm -rf /usr/share/dotnet || true
+          df -h
+          sudo apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
+          sudo apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
+          sudo apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
+          sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
+          df -h
 
       - name: Fetch JSON file
         run: curl -s https://raw.githubusercontent.com/WindowsGSM/SteamAppInfo/refs/heads/main/AppInfo/232250.json -o appinfo.json
